export const abiMetadata = [
  {
    type: "constructor",
    stateMutability: "nonpayable",
    inputs: [
      { type: "address", name: "_jaothuiAddr", internalType: "address" },
      { type: "address", name: "_history", internalType: "address" },
    ],
  },
  {
    type: "event",
    name: "RoleAdminChanged",
    inputs: [
      { type: "bytes32", name: "role", internalType: "bytes32", indexed: true },
      {
        type: "bytes32",
        name: "previousAdminRole",
        internalType: "bytes32",
        indexed: true,
      },
      {
        type: "bytes32",
        name: "newAdminRole",
        internalType: "bytes32",
        indexed: true,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoleGranted",
    inputs: [
      { type: "bytes32", name: "role", internalType: "bytes32", indexed: true },
      {
        type: "address",
        name: "account",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "sender",
        internalType: "address",
        indexed: true,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoleRevoked",
    inputs: [
      { type: "bytes32", name: "role", internalType: "bytes32", indexed: true },
      {
        type: "address",
        name: "account",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "sender",
        internalType: "address",
        indexed: true,
      },
    ],
    anonymous: false,
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bytes32", name: "", internalType: "bytes32" }],
    name: "ADMIN",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bytes32", name: "", internalType: "bytes32" }],
    name: "DEFAULT_ADMIN_ROLE",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "addMetadata",
    inputs: [
      { type: "uint256", name: "_tokenId", internalType: "uint256" },
      {
        type: "tuple",
        name: "_input",
        internalType: "struct JaothuiMetadataManager.InputMetadata",
        components: [
          { type: "string", name: "name", internalType: "string" },
          { type: "uint256", name: "microchip", internalType: "uint256" },
          { type: "string", name: "certNo", internalType: "string" },
          { type: "string", name: "origin", internalType: "string" },
          { type: "string", name: "color", internalType: "string" },
          { type: "string", name: "imageUri", internalType: "string" },
          { type: "string", name: "detail", internalType: "string" },
          { type: "string", name: "sex", internalType: "string" },
          { type: "string", name: "rarity", internalType: "string" },
          { type: "uint256", name: "birthdate", internalType: "uint256" },
          { type: "uint256", name: "height", internalType: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "addMetadataBatch",
    inputs: [
      { type: "uint256[]", name: "_tokenIds", internalType: "uint256[]" },
      {
        type: "tuple[]",
        name: "_inputs",
        internalType: "struct JaothuiMetadataManager.InputMetadata[]",
        components: [
          { type: "string", name: "name", internalType: "string" },
          { type: "uint256", name: "microchip", internalType: "uint256" },
          { type: "string", name: "certNo", internalType: "string" },
          { type: "string", name: "origin", internalType: "string" },
          { type: "string", name: "color", internalType: "string" },
          { type: "string", name: "imageUri", internalType: "string" },
          { type: "string", name: "detail", internalType: "string" },
          { type: "string", name: "sex", internalType: "string" },
          { type: "string", name: "rarity", internalType: "string" },
          { type: "uint256", name: "birthdate", internalType: "uint256" },
          { type: "uint256", name: "height", internalType: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "tuple[]",
        name: "",
        internalType: "struct JaothuiMetadataManager.BUFFALO[]",
        components: [
          { type: "string", name: "name", internalType: "string" },
          { type: "string", name: "origin", internalType: "string" },
          { type: "string", name: "color", internalType: "string" },
          { type: "string", name: "imageUri", internalType: "string" },
          { type: "string", name: "detail", internalType: "string" },
          { type: "string", name: "sex", internalType: "string" },
          { type: "uint256", name: "birthdate", internalType: "uint256" },
          { type: "uint256", name: "height", internalType: "uint256" },
          {
            type: "tuple",
            name: "certify",
            internalType: "struct JaothuiMetadataManager.CERTIFY",
            components: [
              { type: "uint256", name: "microchip", internalType: "uint256" },
              { type: "string", name: "certNo", internalType: "string" },
              { type: "string", name: "rarity", internalType: "string" },
            ],
          },
          {
            type: "tuple",
            name: "relation",
            internalType: "struct JaothuiMetadataManager.RELATION",
            components: [
              {
                type: "uint256",
                name: "motherTokenId",
                internalType: "uint256",
              },
              {
                type: "uint256",
                name: "fatherTokenId",
                internalType: "uint256",
              },
            ],
          },
          { type: "uint256", name: "createdAt", internalType: "uint256" },
          { type: "uint256", name: "updatedAt", internalType: "uint256" },
        ],
      },
    ],
    name: "getAllMetadata",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "tuple",
        name: "",
        internalType: "struct JaothuiMetadataManager.BUFFALO",
        components: [
          { type: "string", name: "name", internalType: "string" },
          { type: "string", name: "origin", internalType: "string" },
          { type: "string", name: "color", internalType: "string" },
          { type: "string", name: "imageUri", internalType: "string" },
          { type: "string", name: "detail", internalType: "string" },
          { type: "string", name: "sex", internalType: "string" },
          { type: "uint256", name: "birthdate", internalType: "uint256" },
          { type: "uint256", name: "height", internalType: "uint256" },
          {
            type: "tuple",
            name: "certify",
            internalType: "struct JaothuiMetadataManager.CERTIFY",
            components: [
              { type: "uint256", name: "microchip", internalType: "uint256" },
              { type: "string", name: "certNo", internalType: "string" },
              { type: "string", name: "rarity", internalType: "string" },
            ],
          },
          {
            type: "tuple",
            name: "relation",
            internalType: "struct JaothuiMetadataManager.RELATION",
            components: [
              {
                type: "uint256",
                name: "motherTokenId",
                internalType: "uint256",
              },
              {
                type: "uint256",
                name: "fatherTokenId",
                internalType: "uint256",
              },
            ],
          },
          { type: "uint256", name: "createdAt", internalType: "uint256" },
          { type: "uint256", name: "updatedAt", internalType: "uint256" },
        ],
      },
    ],
    name: "getMetadata",
    inputs: [{ type: "uint256", name: "_tokenId", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "tuple",
        name: "",
        internalType: "struct JaothuiMetadataManager.BUFFALO",
        components: [
          { type: "string", name: "name", internalType: "string" },
          { type: "string", name: "origin", internalType: "string" },
          { type: "string", name: "color", internalType: "string" },
          { type: "string", name: "imageUri", internalType: "string" },
          { type: "string", name: "detail", internalType: "string" },
          { type: "string", name: "sex", internalType: "string" },
          { type: "uint256", name: "birthdate", internalType: "uint256" },
          { type: "uint256", name: "height", internalType: "uint256" },
          {
            type: "tuple",
            name: "certify",
            internalType: "struct JaothuiMetadataManager.CERTIFY",
            components: [
              { type: "uint256", name: "microchip", internalType: "uint256" },
              { type: "string", name: "certNo", internalType: "string" },
              { type: "string", name: "rarity", internalType: "string" },
            ],
          },
          {
            type: "tuple",
            name: "relation",
            internalType: "struct JaothuiMetadataManager.RELATION",
            components: [
              {
                type: "uint256",
                name: "motherTokenId",
                internalType: "uint256",
              },
              {
                type: "uint256",
                name: "fatherTokenId",
                internalType: "uint256",
              },
            ],
          },
          { type: "uint256", name: "createdAt", internalType: "uint256" },
          { type: "uint256", name: "updatedAt", internalType: "uint256" },
        ],
      },
    ],
    name: "getMetadataByMicrochip",
    inputs: [{ type: "uint256", name: "_microchip", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "tuple[]",
        name: "",
        internalType: "struct JaothuiMetadataManager.BUFFALO[]",
        components: [
          { type: "string", name: "name", internalType: "string" },
          { type: "string", name: "origin", internalType: "string" },
          { type: "string", name: "color", internalType: "string" },
          { type: "string", name: "imageUri", internalType: "string" },
          { type: "string", name: "detail", internalType: "string" },
          { type: "string", name: "sex", internalType: "string" },
          { type: "uint256", name: "birthdate", internalType: "uint256" },
          { type: "uint256", name: "height", internalType: "uint256" },
          {
            type: "tuple",
            name: "certify",
            internalType: "struct JaothuiMetadataManager.CERTIFY",
            components: [
              { type: "uint256", name: "microchip", internalType: "uint256" },
              { type: "string", name: "certNo", internalType: "string" },
              { type: "string", name: "rarity", internalType: "string" },
            ],
          },
          {
            type: "tuple",
            name: "relation",
            internalType: "struct JaothuiMetadataManager.RELATION",
            components: [
              {
                type: "uint256",
                name: "motherTokenId",
                internalType: "uint256",
              },
              {
                type: "uint256",
                name: "fatherTokenId",
                internalType: "uint256",
              },
            ],
          },
          { type: "uint256", name: "createdAt", internalType: "uint256" },
          { type: "uint256", name: "updatedAt", internalType: "uint256" },
        ],
      },
    ],
    name: "getMetadataOf",
    inputs: [{ type: "address", name: "_owner", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bytes32", name: "", internalType: "bytes32" }],
    name: "getRoleAdmin",
    inputs: [{ type: "bytes32", name: "role", internalType: "bytes32" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "grantRole",
    inputs: [
      { type: "bytes32", name: "role", internalType: "bytes32" },
      { type: "address", name: "account", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "hasRole",
    inputs: [
      { type: "bytes32", name: "role", internalType: "bytes32" },
      { type: "address", name: "account", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "history",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "initialized",
    inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "jaothui",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "microchipToTokenId",
    inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "renounceRole",
    inputs: [
      { type: "bytes32", name: "role", internalType: "bytes32" },
      { type: "address", name: "account", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "revokeRole",
    inputs: [
      { type: "bytes32", name: "role", internalType: "bytes32" },
      { type: "address", name: "account", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setCertId",
    inputs: [
      { type: "uint256", name: "_tokenId", internalType: "uint256" },
      { type: "string", name: "_certNo", internalType: "string" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setDetail",
    inputs: [
      { type: "uint256", name: "_tokenId", internalType: "uint256" },
      { type: "string", name: "_detail", internalType: "string" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setHistory",
    inputs: [{ type: "address", name: "_history", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setJaothuiAddress",
    inputs: [
      { type: "address", name: "_jaothuiAddr", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setName",
    inputs: [
      { type: "uint256", name: "_tokenId", internalType: "uint256" },
      { type: "string", name: "_name", internalType: "string" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setParent",
    inputs: [
      { type: "uint256", name: "_tokenId", internalType: "uint256" },
      { type: "uint256", name: "_fatherId", internalType: "uint256" },
      { type: "uint256", name: "_motherId", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setRarity",
    inputs: [
      { type: "uint256", name: "_tokenId", internalType: "uint256" },
      { type: "string", name: "_rarity", internalType: "string" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setUninitialize",
    inputs: [{ type: "uint256", name: "_tokenId", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "supportsInterface",
    inputs: [{ type: "bytes4", name: "interfaceId", internalType: "bytes4" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "string", name: "name", internalType: "string" },
      { type: "string", name: "origin", internalType: "string" },
      { type: "string", name: "color", internalType: "string" },
      { type: "string", name: "imageUri", internalType: "string" },
      { type: "string", name: "detail", internalType: "string" },
      { type: "string", name: "sex", internalType: "string" },
      { type: "uint256", name: "birthdate", internalType: "uint256" },
      { type: "uint256", name: "height", internalType: "uint256" },
      {
        type: "tuple",
        name: "certify",
        internalType: "struct JaothuiMetadataManager.CERTIFY",
        components: [
          { type: "uint256", name: "microchip", internalType: "uint256" },
          { type: "string", name: "certNo", internalType: "string" },
          { type: "string", name: "rarity", internalType: "string" },
        ],
      },
      {
        type: "tuple",
        name: "relation",
        internalType: "struct JaothuiMetadataManager.RELATION",
        components: [
          { type: "uint256", name: "motherTokenId", internalType: "uint256" },
          { type: "uint256", name: "fatherTokenId", internalType: "uint256" },
        ],
      },
      { type: "uint256", name: "createdAt", internalType: "uint256" },
      { type: "uint256", name: "updatedAt", internalType: "uint256" },
    ],
    name: "tokenIdToUri",
    inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "totalMetadata",
    inputs: [],
  },
];
